### ISSUE TITLE
Seqsplit.go  Does not create fasta file with an ID?

### ISSUE THREAD

**Issue by jo-mc** [biogo/examples#12]
### What are you trying to do?
Run seqplit and use fasta output  in another package

### What did you do?
Looked at the output and found the created fasta file has a space after '>' and the description  (as suspected from the code), no ID is set.
Changing 'curr.Desc' on lines 119 and 129  to 'curr.ID' fixed the problem.

### What did you expect to happen?
Valid fasta file to be created, is blank ID ok? The word following the ">" symbol is the identifier, I guess it doesn't actually say if a space is allowed  - but convention does not seem to support this. (I have not found the original spec)

### What actually happened?
Fasta output file has a space between > and the name/id/descriptor "> name" 

### What version of Go and bíogo are you using?

go version go1.16.3 linux/amd64

**Comment by kortschak** [comment]
Fixed by #13
