### ISSUE TITLE
Error, no target provided !!!

### ISSUE THREAD

**Issue by Yuma248** [biogo/examples#14]
I am having problems with the Krishna alignment package, I install al locally and looks like works, but when I run the command 

krishna -tmp=./ -threads=2 -log -filtid=0.90 -filtlen=200 -target=chr8.fa -query=chr9.fa -out=chr8_chr9.gff

It says

krishna:2023/03/14 09:50:23 No target provided.

But the chr8.fa and chr9.fa files are in the working directory. Do you have an idea what could be the problem?

Thanks in advance

**Comment by kortschak** [comment]
Pleas paste the full log output.

**Comment by Yuma248** [comment]
Thanks for your replay, but it does not even produce a log file, it produces the gff files but they are all empty. Here is the whole  std output 

krishna -tmp=./ -threads=2 -log -filtid=0.90 -filtlen=200 -target=chr8.fa -query=chr9.fa -out=chr8_chr9.gff
krishna:2023/03/15 11:10:21 [krishna -tmp=./ -threads=2 -log -filtid=0.90 -filtlen=200 -target=chr8.fa -query=chr9.fa -out=chr8_chr9.gff]
krishna:2023/03/15 11:10:21 No target provided.


Thanks again

**Comment by kortschak** [comment]
That is the log output.

Please paste the output of `go env` and `go version`. Can you also tell me what the sha1 of the commit that you are building from is (`git rev-parse HEAD` in your local biogo/examples repo).

(Note, please paste code in code blocks to make spacing consistent).

**Comment by Yuma248** [comment]
Hi Kortschak, sorry to take me this long, I think the problem was related to my conda env, where I had installed go and other software. I rebuilt the whole thing and not it is working.  Thanks a lot for your help.
