### ISSUE TITLE
krishna: clean up seqer and matrix code

### ISSUE THREAD

**Issue by kortschak** [biogo/examples#7]
This involves putting seqer and matrix in their own cmd directories and possibly generating or otherwise the options in matrix.

/cc @dadelson @luzengAdelaide

**Comment by luzengAdelaide** [comment]
@kortschak Please add executable of krishna-matrix, gffer and seqer. Can we also change the default malloc.go running time to 40 to handle big jobs?
 
/cc @dadelson

**Comment by kortschak** [comment]
>Can we also change the default malloc.go running time to 40 to handle big jobs?

No, this is not in our hands.

The original problem with the `matrix` program was that it needed to be altered for each krishna job set. What I will do is get `matrix` to take a string parameter called `krishnaflags` that is organised appropriately to send to `krishna`.

**Comment by luzengAdelaide** [comment]
Yeah, you right! That's what we just talked about, please do that, so we don't need to build every time after change krishna parameters.
